import { signIn } from "next-auth/react";
import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  const handleSignIn = () => {
    signIn();
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>This shit works</div>
        <button onClick={handleSignIn}>Sign In</button>
      </main>
    </div>
  );
}
