import Head from "next/head";
// import { useUserAuthContext } from "../components/contexts/UserAuthContextProvider";


const Login = () => {
  // const { signIn } = useUserAuthContext();

  // const handleSignIn = () => {
  //   signIn();
  // };

  return (
    <div >
      <Head>
        <title>Our Scene - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>Would you like to sign in please?</div>
        <button >Sign In</button>
      </main>
    </div>
  );
};

export default Login;
