import Head from "next/head";
import { useUserAuthContext } from "../components/contexts/UserAuthContextProvider";
import styles from "../styles/Home.module.css";

const Login = () => {
  const { signIn } = useUserAuthContext();

  const handleSignIn = () => {
    signIn();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Our Scene - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>Would you like to sign in please?</div>
        <button onClick={handleSignIn}>Sign In</button>
      </main>
    </div>
  );
};

export default Login;
